version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      elastic:
        patterns:
          - '@elastic/*'
      mcp:
        patterns:
          - '@modelcontextprotocol/*'
